// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitApplication() *application {
	appConfig := providerAppConfig()
	store := providerStore(appConfig)
	cmdCommand := providerCommand(store)
	server := providerServer(store)
	mainApplication := providerApplication(appConfig, store, cmdCommand, server)
	return mainApplication
}
